// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('editEvent', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('editEvent', async function() {
    await driver.get("http://127.0.0.1:5501/interface/pages/mural.html")
    await driver.manage().window().setRect({ width: 1050, height: 748 })
    await driver.findElement(By.css(".button-cards-one")).click()
    await driver.findElement(By.css("#modall > #modal-content #selection")).click()
    {
      const dropdown = await driver.findElement(By.css("#modall > #modal-content #selection"))
      await dropdown.findElement(By.xpath("//option[. = 'Apresentation']")).click()
    }
    await driver.findElement(By.css("#modall > #modal-content #nameEv")).click()
    await driver.findElement(By.css("#modall > #modal-content #nameEv")).sendKeys("Nascismento")
    await driver.findElement(By.css("#modall > #modal-content #dateEv")).click()
    await driver.findElement(By.css("#modall > #modal-content #dateEv")).sendKeys("0002-05-25")
    await driver.findElement(By.css("#modall > #modal-content #dateEv")).sendKeys("0020-05-25")
    await driver.findElement(By.css("#modall > #modal-content #dateEv")).sendKeys("0200-05-25")
    await driver.findElement(By.css("#modall > #modal-content #dateEv")).sendKeys("2000-05-25")
    await driver.findElement(By.css("#modall > #modal-content #timeEv")).click()
    await driver.findElement(By.css("#modall > #modal-content #timeEv")).sendKeys("12:00")
    await driver.findElement(By.css("#modall > #modal-content #placeEv")).click()
    await driver.findElement(By.css("#modall > #modal-content #placeEv")).sendKeys("Belém")
    await driver.findElement(By.css("#modall > #modal-content #desc")).sendKeys("Salvation")
    await driver.findElement(By.css("#modall > #modal-content #btn > #btn")).click()
  })
})
