// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('loginTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('loginTest', async function() {
    await driver.get("http://127.0.0.1:5501/index.html")
    await driver.manage().window().setRect({ width: 1050, height: 748 })
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("teste@test.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("12345678")
    await driver.findElement(By.css("button")).click()
    await driver.close()
  })
})
